### ISSUE TITLE
Übersicht mit Stationen und entsprechenden Dokumenten

### ISSUE THREAD

**Issue by SebastianVonRotz** [janikvonrotz/labtrail#6]
Bei vielen Stationen und Dokumenten ist es schwierig den Überblick zu haben welche Stationen wieviele und welche Dokumente haben (man müsste sich durch jede Station "durchklicken")

**Describe the solution you'd like**
Eine Seite welche Alle Stationen und zugehörigen Dokumente auflistet um einen Überblick zu erhalten

**Comment by janikvonrotz** [comment]
@SebastianVonRotz könnte man auch die aktuelle Stationsansicht mit den Dokumenten ergänzen. Also Beispielsweise mit einer Spalte "Dokumente", die die Anzahl der verlinkten Dokumente anzeigt.

**Comment by SebastianVonRotz** [comment]
Ja, das wäre auch eine Lösung, sieht man dann nur die Anzahl oder auch Kategorie des angehängten Dokuments?

Wäre es auch möglich bei der Stationsübersicht die zugehörigen Dokumente aufklappen zulassen? Wie beispielsweise:
--------------------------------
˃ Station XY
˅ Station XY
     ˃SOP 
     ˃ INFO 
˃ Station XY
˃ Station XY
--------------------------------

Oder ist es zu aufwendig zum integrieren?

**Comment by janikvonrotz** [comment]
Dein Vorschlag wäre auch machbar. Aber dann wird die Tabellen-Ansicht überflüssig.

Könnte auch eine Spalte mit Auflistung machen. Beispielsweise: 
![grafik](https://user-images.githubusercontent.com/1370421/75178202-f3017c00-5737-11ea-931d-2d6c33b1747d.png)

**Comment by janikvonrotz** [comment]
Oder: 
![grafik](https://user-images.githubusercontent.com/1370421/75178255-13313b00-5738-11ea-8a4d-da9258f1c9c4.png)

**Comment by SebastianVonRotz** [comment]
Ah ja die documents kolonne wäre gut so, also wie die im 2ten Bild.

**Comment by janikvonrotz** [comment]
Done

**Comment by SebastianVonRotz** [comment]
Zeigt nur beim R10/11 die Documents and jedoch nicht bei den anderen Stationen
